"use server";

import { auth } from "@/../auth";
import { prisma } from "@/lib/prisma";
import { hasPermission } from "@/lib/permissions";
import { maskTail } from "@/lib/hr/crypto";

// ============================================================
// Statutory REGISTERS (reconciliation, NOT filed returns)
// ------------------------------------------------------------
// Read-only summary registers over frozen HrPayslip snapshots for a single
// payroll run (fy + month). These are the per-employee reconciliation views HR
// uses to tie payroll out against the numbers before the actual RETURN files
// (PF ECR, ESI, PT challan, Form 24Q) are generated by a separate process.
//
// NOTHING here files a return, mutates data, or decrypts a statutory ID.
// Statutory IDs (UAN / PF no / ESI no) are shown MASKED via maskTail.
// Guarded by hr:payroll. LOCKED / PAID runs only (finalised figures).
// ============================================================

const FINAL_STATUSES = ["LOCKED", "PAID"] as const;

async function requireRole(): Promise<string | null> {
  const session = await auth();
  const role = session?.user?.role;
  if (!role || !hasPermission(role, "hr:payroll")) return null;
  return role;
}

const round = (n: unknown) => Math.round(Number(n) || 0);

export interface StatutoryPeriod {
  fy: string;
  month: number;
  label: string;
  status: string;
  headcount: number;
}

/**
 * Distinct finalised (LOCKED / PAID) payroll periods, newest first, for the
 * FY + month picker. Draft runs are intentionally excluded — a register is only
 * meaningful once the run is locked.
 */
export async function listStatutoryPeriods(): Promise<StatutoryPeriod[]> {
  const role = await requireRole();
  if (!role) return [];
  const runs = await prisma.hrPayrollRun.findMany({
    where: { status: { in: [...FINAL_STATUSES] } },
    orderBy: [{ fy: "desc" }, { month: "desc" }],
    select: { fy: true, month: true, label: true, status: true, headcount: true },
  });
  return runs;
}

interface RunMeta {
  fy: string;
  month: number;
  runLabel: string | null;
  runStatus: string | null;
  found: boolean;
}

/** Locate a finalised run for (fy, month). Returns null if none / not final. */
async function findFinalRun(fy: string, month: number) {
  if (!fy || !month) return null;
  return prisma.hrPayrollRun.findFirst({
    where: { fy, month, status: { in: [...FINAL_STATUSES] } },
  });
}

/** Statutory-ID lookup for a set of employees, keyed by employeeId. */
async function statutoryMap(employeeIds: string[]) {
  const rows = await prisma.employeeStatutory.findMany({
    where: { employeeId: { in: employeeIds } },
    select: { employeeId: true, uan: true, pf: true, esi: true },
  });
  return new Map(rows.map((r) => [r.employeeId, r]));
}

// ------------------------------------------------------------
// 1) PF contribution register (reconciliation, NOT the ECR file)
// ------------------------------------------------------------
export interface PfRegisterRow {
  employeeId: string;
  empCode: string;
  name: string;
  uanMasked: string | null;
  pfNoMasked: string | null;
  employeePf: number;
  employerEps: number;
  employerEpf: number;
  edli: number;
  admin: number;
  total: number;
}
export interface PfRegister extends RunMeta {
  rows: PfRegisterRow[];
  totals: {
    employeePf: number;
    employerEps: number;
    employerEpf: number;
    edli: number;
    admin: number;
    total: number;
    headcount: number;
  };
}

export async function getPfRegister(input: { fy: string; month: number }): Promise<PfRegister> {
  const base: PfRegister = {
    fy: input.fy,
    month: input.month,
    runLabel: null,
    runStatus: null,
    found: false,
    rows: [],
    totals: { employeePf: 0, employerEps: 0, employerEpf: 0, edli: 0, admin: 0, total: 0, headcount: 0 },
  };
  const role = await requireRole();
  if (!role) return base;

  const run = await findFinalRun(input.fy, input.month);
  if (!run) return base;

  const slips = await prisma.hrPayslip.findMany({
    where: { runId: run.id },
    orderBy: { empCodeSnap: "asc" },
    select: {
      employeeId: true,
      empCodeSnap: true,
      nameSnap: true,
      pf: true,
      employerEps: true,
      employerEpf: true,
      employerEdli: true,
      employerPfAdmin: true,
    },
  });
  const ids = await statutoryMap(slips.map((s) => s.employeeId));

  const rows: PfRegisterRow[] = slips.map((s) => {
    const st = ids.get(s.employeeId);
    const employeePf = round(s.pf);
    const employerEps = round(s.employerEps);
    const employerEpf = round(s.employerEpf);
    const edli = round(s.employerEdli);
    const admin = round(s.employerPfAdmin);
    return {
      employeeId: s.employeeId,
      empCode: s.empCodeSnap,
      name: s.nameSnap,
      uanMasked: maskTail(st?.uan, 4),
      pfNoMasked: maskTail(st?.pf, 4),
      employeePf,
      employerEps,
      employerEpf,
      edli,
      admin,
      total: employeePf + employerEps + employerEpf + edli + admin,
    };
  });

  const totals = rows.reduce(
    (t, r) => ({
      employeePf: t.employeePf + r.employeePf,
      employerEps: t.employerEps + r.employerEps,
      employerEpf: t.employerEpf + r.employerEpf,
      edli: t.edli + r.edli,
      admin: t.admin + r.admin,
      total: t.total + r.total,
      headcount: t.headcount + 1,
    }),
    base.totals,
  );

  return { ...base, runLabel: run.label, runStatus: run.status, found: true, rows, totals };
}

// ------------------------------------------------------------
// 2) ESI contribution register (reconciliation, NOT the ESI return)
// ------------------------------------------------------------
export interface EsiRegisterRow {
  employeeId: string;
  empCode: string;
  name: string;
  esiNoMasked: string | null;
  employeeEsi: number;
  employerEsi: number;
  total: number;
}
export interface EsiRegister extends RunMeta {
  rows: EsiRegisterRow[];
  totals: { employeeEsi: number; employerEsi: number; total: number; headcount: number };
}

export async function getEsiRegister(input: { fy: string; month: number }): Promise<EsiRegister> {
  const base: EsiRegister = {
    fy: input.fy,
    month: input.month,
    runLabel: null,
    runStatus: null,
    found: false,
    rows: [],
    totals: { employeeEsi: 0, employerEsi: 0, total: 0, headcount: 0 },
  };
  const role = await requireRole();
  if (!role) return base;

  const run = await findFinalRun(input.fy, input.month);
  if (!run) return base;

  const slips = await prisma.hrPayslip.findMany({
    where: { runId: run.id },
    orderBy: { empCodeSnap: "asc" },
    select: { employeeId: true, empCodeSnap: true, nameSnap: true, esi: true, employerEsi: true },
  });
  const ids = await statutoryMap(slips.map((s) => s.employeeId));

  // Only employees with an ESI leg (or an ESI number on file) belong here.
  const rows: EsiRegisterRow[] = slips
    .map((s) => {
      const st = ids.get(s.employeeId);
      const employeeEsi = round(s.esi);
      const employerEsi = round(s.employerEsi);
      return {
        employeeId: s.employeeId,
        empCode: s.empCodeSnap,
        name: s.nameSnap,
        esiNoMasked: maskTail(st?.esi, 4),
        employeeEsi,
        employerEsi,
        total: employeeEsi + employerEsi,
      };
    })
    .filter((r) => r.employeeEsi > 0 || r.employerEsi > 0 || r.esiNoMasked);

  const totals = rows.reduce(
    (t, r) => ({
      employeeEsi: t.employeeEsi + r.employeeEsi,
      employerEsi: t.employerEsi + r.employerEsi,
      total: t.total + r.total,
      headcount: t.headcount + 1,
    }),
    base.totals,
  );

  return { ...base, runLabel: run.label, runStatus: run.status, found: true, rows, totals };
}

// ------------------------------------------------------------
// 3) PT register — per-employee PT, grouped by the entity's PT state
// ------------------------------------------------------------
export interface PtRegisterRow {
  employeeId: string;
  empCode: string;
  name: string;
  state: string; // resolved PT state label ("—" when the entity has none set)
  pt: number;
}
export interface PtStateGroup {
  state: string;
  rows: PtRegisterRow[];
  subtotal: number;
}
export interface PtRegister extends RunMeta {
  groups: PtStateGroup[];
  totals: { pt: number; headcount: number };
}

export async function getPtRegister(input: { fy: string; month: number }): Promise<PtRegister> {
  const base: PtRegister = {
    fy: input.fy,
    month: input.month,
    runLabel: null,
    runStatus: null,
    found: false,
    groups: [],
    totals: { pt: 0, headcount: 0 },
  };
  const role = await requireRole();
  if (!role) return base;

  const run = await findFinalRun(input.fy, input.month);
  if (!run) return base;

  const slips = await prisma.hrPayslip.findMany({
    where: { runId: run.id },
    orderBy: { empCodeSnap: "asc" },
    select: { employeeId: true, empCodeSnap: true, nameSnap: true, pt: true },
  });

  // Resolve each employee's PT state via their legal entity's statutory config.
  const employees = await prisma.employee.findMany({
    where: { id: { in: slips.map((s) => s.employeeId) } },
    select: {
      id: true,
      legalEntity: { select: { name: true, statutoryConfig: { select: { ptState: true } } } },
    },
  });
  const stateByEmp = new Map(
    employees.map((e) => [
      e.id,
      e.legalEntity?.statutoryConfig?.ptState?.trim() || "—",
    ]),
  );

  const rows: PtRegisterRow[] = slips
    .map((s) => ({
      employeeId: s.employeeId,
      empCode: s.empCodeSnap,
      name: s.nameSnap,
      state: stateByEmp.get(s.employeeId) ?? "—",
      pt: round(s.pt),
    }))
    .filter((r) => r.pt > 0);

  const byState = new Map<string, PtRegisterRow[]>();
  for (const r of rows) {
    const arr = byState.get(r.state) ?? [];
    arr.push(r);
    byState.set(r.state, arr);
  }
  const groups: PtStateGroup[] = [...byState.entries()]
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map(([state, grp]) => ({
      state,
      rows: grp,
      subtotal: grp.reduce((s, r) => s + r.pt, 0),
    }));

  const totals = {
    pt: rows.reduce((s, r) => s + r.pt, 0),
    headcount: rows.length,
  };

  return { ...base, runLabel: run.label, runStatus: run.status, found: true, groups, totals };
}

// ------------------------------------------------------------
// 4) Statutory summary — one row per statute with the run total
// ------------------------------------------------------------
export interface StatutorySummaryRow {
  key: string;
  statute: string;
  note: string;
  amount: number;
}
export interface StatutorySummary extends RunMeta {
  headcount: number;
  rows: StatutorySummaryRow[];
  grandTotal: number;
}

export async function getStatutorySummary(input: { fy: string; month: number }): Promise<StatutorySummary> {
  const base: StatutorySummary = {
    fy: input.fy,
    month: input.month,
    runLabel: null,
    runStatus: null,
    found: false,
    headcount: 0,
    rows: [],
    grandTotal: 0,
  };
  const role = await requireRole();
  if (!role) return base;

  const run = await findFinalRun(input.fy, input.month);
  if (!run) return base;

  const agg = await prisma.hrPayslip.aggregate({
    where: { runId: run.id },
    _count: { _all: true },
    _sum: {
      pf: true,
      esi: true,
      pt: true,
      tds: true,
      employerEps: true,
      employerEpf: true,
      employerEdli: true,
      employerPfAdmin: true,
      employerEsi: true,
    },
  });
  const s = agg._sum;

  const rows: StatutorySummaryRow[] = [
    { key: "pfEe", statute: "PF — Employee (A/c 1)", note: "12% of PF wages, deducted from employee", amount: round(s.pf) },
    { key: "pfEr", statute: "PF — Employer (A/c 1, ex-pension)", note: "Employer EPF share", amount: round(s.employerEpf) },
    { key: "eps", statute: "EPS — Pension (A/c 10)", note: "Employer 8.33% pension leg", amount: round(s.employerEps) },
    { key: "edli", statute: "EDLI (A/c 21)", note: "Employer insurance leg", amount: round(s.employerEdli) },
    { key: "admin", statute: "PF Admin (A/c 2)", note: "Employer administration charges", amount: round(s.employerPfAdmin) },
    { key: "esiEe", statute: "ESI — Employee", note: "0.75% employee contribution", amount: round(s.esi) },
    { key: "esiEr", statute: "ESI — Employer", note: "3.25% employer contribution", amount: round(s.employerEsi) },
    { key: "pt", statute: "Professional Tax (PT)", note: "State professional tax deducted", amount: round(s.pt) },
    { key: "tds", statute: "TDS (Income Tax, 24Q)", note: "Income tax deducted at source", amount: round(s.tds) },
  ];

  return {
    ...base,
    runLabel: run.label,
    runStatus: run.status,
    found: true,
    headcount: agg._count._all,
    rows,
    grandTotal: rows.reduce((t, r) => t + r.amount, 0),
  };
}
