// Auto-generated Operations deep-audit checklist (pre-launch gate).
export interface OpsAuditSeedItem { category: string; title: string; critical: boolean }
export const OPS_AUDIT_CHECKLIST: OpsAuditSeedItem[] = [
  { category: "Statutory Compliance", title: "Occupancy Certificate (OC) from BBMP obtained and matches the as-built structure; no deviations from sanctioned plan", critical: true },
  { category: "Statutory Compliance", title: "Fire NOC / Fire Licence from Karnataka State Fire & Emergency Services valid and displayed; occupant-load certified for each hall matches seating layouts", critical: true },
  { category: "Statutory Compliance", title: "Trade Licence (BBMP), FSSAI food licence (central/state) for in-house & empanelled caterers, and Bar/Excise (CL-7/temporary event) licence framework in place", critical: true },
  { category: "Statutory Compliance", title: "Building Stability Certificate from licensed structural engineer and lift/elevator licence (Karnataka Lifts Act) on record", critical: true },
  { category: "Statutory Compliance", title: "Pollution Control Board (KSPCB) consent for DG sets, STP and noise; banquet sound-limit (deadline ~10 PM, 55–65 dB residential) SOP documented", critical: false },
  { category: "Statutory Compliance", title: "PESO licence for LPG bullet/manifold and bulk fuel storage; insurance (public liability, fire, asset) policies active and event-coverage rider confirmed", critical: true },
  { category: "Fire & Life Safety", title: "All fire extinguishers (ABC/CO2/K-type in kitchen) pressure-tested, wall-mounted at code spacing, tagged with next-refill date; staff trained on use", critical: true },
  { category: "Fire & Life Safety", title: "Sprinkler system, wet/dry risers, hydrants, hose reels, fire pump (jockey/main/diesel) and terrace + underground water tank fire-reserve tested at rated pressure", critical: true },
  { category: "Fire & Life Safety", title: "Smoke/heat detectors, manual call points, fire alarm panel and PA/voice-evacuation system zoned, tested hall-by-hall, and audible over peak DJ/baraja volume", critical: true },
  { category: "Fire & Life Safety", title: "Emergency exits unobstructed, panic-bar hardware functional, exit signage illuminated with battery backup, and exit count/width matches certified occupant load per hall", critical: true },
  { category: "Fire & Life Safety", title: "Kitchen hood fire-suppression (Ansul/K-type), gas-leak detectors with auto-shutoff solenoid, and DG/transformer-room fire separation verified", critical: true },
  { category: "Fire & Life Safety", title: "Assembly point marked, evacuation maps posted at every hall/landing, and one full fire drill conducted with ops + valet + kitchen staff before inauguration", critical: true },
  { category: "Fire & Life Safety", title: "Mandap/havan/fire-ritual SOP: heat-resistant base, sand buckets, dedicated extinguisher, smoke-detector isolation procedure, and ventilation for sacred-fire ceremonies", critical: true },
  { category: "Utilities & Power", title: "BESCOM sanctioned load energized; DG set(s) sized for 100% load incl. HVAC, auto-changeover (AMF) tested, and load-bank/blackout drill passes within seconds", critical: true },
  { category: "Utilities & Power", title: "UPS/inverter backup for emergency lighting, lifts, fire systems, kitchen cold storage and AV controls verified on mains failure", critical: true },
  { category: "Utilities & Power", title: "Electrical earthing, ELCB/RCCB, panel labeling, and event power tap-off points (stage/DJ/lighting/catering) with spare capacity load-tested", critical: true },
  { category: "Utilities & Power", title: "HVAC/central AC achieves target temperature for full-occupancy banquet within ramp time; chillers, AHUs and fresh-air make-up balanced per hall", critical: false },
  { category: "Utilities & Power", title: "Domestic water (Cauvery/borewell/tanker), overhead & underground tank capacity for peak event day, pressure at all toilets/kitchens, and water-quality test passed", critical: true },
  { category: "Utilities & Power", title: "STP/ETP commissioned and running; sewage lines, grease traps and storm-water drains tested with no backflow/odour under simulated peak load", critical: true },
  { category: "Guest Experience", title: "Guest toilets (incl. ladies, accessible/divyangjan, baby-care) fully fitted, water/flush/exhaust working, and toilet-to-guest ratio adequate for max event size", critical: true },
  { category: "Guest Experience", title: "Wheelchair access, ramps, accessible lift, and barrier-free path from drop-off to every hall and washroom verified", critical: true },
  { category: "Guest Experience", title: "Lighting levels (ambient, decor, photography, emergency) commissioned per hall; dimming and DMX scenes tested for haldi/sangeet/wedding/reception modes", critical: false },
  { category: "Guest Experience", title: "Parking + valet flow, signage and capacity validated for peak guest count; multi-event simultaneous flow (multi-venue) does not cross-block", critical: true },
  { category: "Guest Experience", title: "Bridal/groom green rooms, VIP lounge, pooja room and changing areas furnished, AC, mirror-lit, lockable and with attached washroom", critical: false },
  { category: "Guest Experience", title: "Wayfinding signage, reception/welcome desk, cloak/gift counter and stage backdrop/branding positions finalized; acoustics checked for speech + music", critical: false },
  { category: "Back-of-House", title: "Commercial kitchen / pantry commissioned: gas manifold leak-tested, exhaust/chimney drawing, cold rooms holding temp, and FSSAI hygiene zoning compliant", critical: true },
  { category: "Back-of-House", title: "Caterer staging, plating, dishwash and wet-garbage segregation areas functional with adequate power, water and drainage", critical: false },
  { category: "Back-of-House", title: "Service corridors, goods lift, and BOH-to-hall routes allow food/decor movement without crossing guest paths; dolly/trolley access clear", critical: false },
  { category: "Back-of-House", title: "Garbage room, wet/dry waste segregation, and licensed waste-vendor pickup SOP set; pest-control contract active and first treatment done", critical: false },
  { category: "Back-of-House", title: "Housekeeping store, linen, ops office, staff toilet/changing and security room equipped and staffed-ready", critical: false },
  { category: "Back-of-House", title: "Inventory of chairs, tables, crockery, linen, buffet counters and decor base structures counted, condition-checked and stored", critical: false },
  { category: "Event Operability", title: "AV/DJ/stage: sound system, mics, mixer, projector/LED wall, and power redundancy dry-run at full volume passes without tripping or feedback", critical: false },
  { category: "Event Operability", title: "Decor rigging/truss anchor points and ceiling load limits certified; baraat entry route, doli/horse/vehicle access and crackerfree-zone SOP defined", critical: true },
  { category: "Event Operability", title: "CCTV coverage (entries, halls, parking, BOH, cash points) live and recording; control room manned-ready with NVR storage verified", critical: true },
  { category: "Event Operability", title: "Wi-Fi/internet, billing/POS, BMS and access-control systems online and tested for live-event load", critical: false },
  { category: "Event Operability", title: "Dummy/mock event run-through completed end-to-end (guest arrival to clearance) with ops, F&B, security and housekeeping; punch-list closed", critical: true },
  { category: "Event Operability", title: "First-aid room/kit, AED, on-call doctor/ambulance tie-up, and emergency contact board (fire, police, hospital) posted", critical: true },
  { category: "Event Operability", title: "Security deployment plan, baggage/metal-detection at entry, bouncer/crowd-control SOP, and night-event lighting on approach roads confirmed", critical: false },
  { category: "Event Operability", title: "Handover dossier complete: as-built drawings, equipment manuals, AMC/warranty contacts, statutory certificates, and emergency SOPs filed with Ops", critical: false },
];
