import { prisma } from "@/lib/prisma";
import { defaultManagementAgreement } from "@/lib/acq/contract-template";

export const runtime = "nodejs";

// ============================================================
// Contract — branded, print-to-PDF agreement document.
// Accessible by the unguessable id so it can be shared with the owner
// (who has no login) for review and signing.
// ============================================================

const PLUM = "#2D1B3D";
const GOLD = "#C9A96E";
const IVORY = "#FAF7F2";

function esc(s: string): string {
  return s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c] as string));
}

const inr = (n: number) => "₹" + Math.round(n).toLocaleString("en-IN");

/** Render the agreement text: numbered clauses become bold headings. */
function renderBody(body: string): string {
  const lines = body.split("\n");
  const out: string[] = [];
  let para: string[] = [];
  const flush = () => {
    if (para.length) {
      out.push(`<p>${esc(para.join(" "))}</p>`);
      para = [];
    }
  };
  for (const raw of lines) {
    const line = raw.trim();
    if (line === "") {
      flush();
      continue;
    }
    if (/^\d+\.\s+[A-Z]/.test(line)) {
      flush();
      out.push(`<h3 class="clause">${esc(line)}</h3>`);
    } else if (/^[A-Z][A-Z\s&]{6,}$/.test(line)) {
      flush();
      out.push(`<h2 class="doctitle">${esc(line)}</h2>`);
    } else {
      para.push(line);
    }
  }
  flush();
  return out.join("\n");
}

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const c = await prisma.acqContract.findFirst({ where: { id, deletedAt: null } });
  if (!c) return new Response("Not found", { status: 404 });

  const body =
    c.body && c.body.trim().length > 0
      ? c.body
      : defaultManagementAgreement({
          ownerName: c.ownerName,
          propertyName: c.propertyName,
          model: c.model,
          baseFeePct: c.baseFeePct ? Number(c.baseFeePct) : null,
          incentivePct: c.incentivePct ? Number(c.incentivePct) : null,
          termYears: c.termYears,
          contractValue: c.contractValue ? Number(c.contractValue) : null,
        });

  const commercials = `
    <table class="terms">
      <tr><td>Commercial model</td><td>${esc(c.model ?? "—")}</td></tr>
      <tr><td>Base fee</td><td>${c.baseFeePct != null ? esc(String(c.baseFeePct)) + "%" : "—"}</td></tr>
      <tr><td>Incentive fee</td><td>${c.incentivePct != null ? esc(String(c.incentivePct)) + "%" : "—"}</td></tr>
      <tr><td>Term</td><td>${c.termYears != null ? esc(String(c.termYears)) + " years" : "—"}</td></tr>
      <tr><td>Indicative contract value</td><td>${c.contractValue != null ? inr(Number(c.contractValue)) : "—"}</td></tr>
    </table>`;

  const html = `<!doctype html><html><head><meta charset="utf-8"/>
<title>${esc(c.title)}</title>
<style>
  @page { size: A4; margin: 22mm 18mm; }
  * { box-sizing: border-box; }
  body { font-family: Georgia, "Times New Roman", serif; color: ${PLUM}; line-height: 1.55; font-size: 12px; }
  .head { border-bottom: 3px solid ${GOLD}; padding-bottom: 12px; margin-bottom: 18px; display:flex; justify-content:space-between; align-items:flex-end; }
  .brand { font-size: 22px; font-weight: 700; letter-spacing: 0.5px; }
  .brand small { display:block; font-size: 10px; letter-spacing: 2px; color: ${GOLD}; font-weight:600; }
  .meta { text-align:right; font-size: 10px; color:#6b6b6b; }
  h2.doctitle { text-align:center; font-size: 16px; letter-spacing: 1px; margin: 8px 0 18px; }
  h3.clause { font-size: 12.5px; margin: 16px 0 4px; }
  p { margin: 4px 0; text-align: justify; }
  .terms { width: 100%; border-collapse: collapse; margin: 14px 0; background: ${IVORY}; }
  .terms td { padding: 6px 10px; border: 1px solid #e7ddc9; }
  .terms td:first-child { font-weight: 600; width: 45%; }
  .sigs { margin-top: 42px; display:flex; gap: 40px; }
  .sig { flex:1; }
  .sig .line { border-top: 1px solid ${PLUM}; margin-top: 46px; padding-top: 4px; font-size: 11px; }
  .foot { margin-top: 30px; border-top: 1px solid #e7ddc9; padding-top: 8px; font-size: 9px; color:#8a8a8a; text-align:center; }
  @media print { .noprint { display:none; } }
</style></head><body>
  <div class="head">
    <div class="brand">Veloria Grand<small>PREMIER VENUES</small></div>
    <div class="meta">Contract ref: ${esc(c.id.slice(-8).toUpperCase())}<br/>Status: ${esc(c.status)}</div>
  </div>
  ${renderBody(body)}
  <h3 class="clause">SCHEDULE — COMMERCIAL TERMS</h3>
  ${commercials}
  <div class="sigs">
    <div class="sig"><div class="line">For the Owner — ${esc(c.ownerName)}</div></div>
    <div class="sig"><div class="line">For Veloria Grand</div></div>
  </div>
  <div class="foot">This document was generated by Veloria Grand CRM. Property: ${esc(c.propertyName)}.</div>
  <script class="noprint">window.onload = () => { setTimeout(() => window.print(), 350); };</script>
</body></html>`;

  return new Response(html, { headers: { "Content-Type": "text/html; charset=utf-8" } });
}
